main:
  # Set this to null if you are running in prod
  project_name: aimingmed-ai
  experiment_name: development
  steps: all
etl:
  input_artifact_name: documents
  document_folder: documents
  path_document_folder: "../../../../data"
  run_id_documents: None
  embedding_model: paraphrase-multilingual-mpnet-base-v2
prompt_engineering:
  run_id_chromadb: None
  chat_model_provider: gemini
  query: "如何治疗乳腺癌?"
  