main:
  # Set this to null if you are running in prod
  project_name: aimingmed-ai
  experiment_name: development
  steps: all
etl:
  document_folder: "documents"
  path_document_folder: "../../../../data"
  embedding_model: "paraphrase-multilingual-mpnet-base-v2"
  
