main:
  # Set this to null if you are running in prod
  project_name: aimingmed-ai
  experiment_name: development
  steps: all
etl:
  input_artifact_name: documents
  document_folder: documents
  path_document_folder: "../../../../data"
  run_id_documents: None
  embedding_model: paraphrase-multilingual-mpnet-base-v2
rag:
  run_id_chromadb: None
  chat_model_provider: deepseek
testing:
  query: "如何治疗乳腺癌?"
evaluation:
  evaluation_dataset_csv_path: "../../../../data/qa_dataset_01.csv"
  evaluation_dataset_column_question: question
  evaluation_dataset_column_answer: answer
  ls_chat_model_provider:
  - gemini
  - deepseek
  - moonshot