####### BUILDER IMAGE #######
# Build stage
FROM node:alpine

WORKDIR /usr/src/app

# Copy everything else, test and build
COPY . /usr/src/app

# Build the app with a specific .env file
ARG ENV_FILE=.env.test
COPY ${ENV_FILE} /usr/src/app/.env

# Copy dependency files and install dependencies
RUN npm install && npm i --save-dev @types/jest

EXPOSE 80
CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "80" ]