services:
  # streamlit:
  #   build: ./streamlit
  #   platform: linux/amd64
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - ./llmops/src/rag_cot_evaluation/chroma_db:/app/llmops/src/rag_cot_evaluation/chroma_db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    platform: linux/amd64
    # command: pipenv run uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8765
    volumes:
      - ./backend:/home/app/backend
    ports:
      - "8004:80"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3004:80"
    depends_on:
      - backend
    environment:
      LOG_LEVEL: "DEBUG"

  tests:
    build:
      context: ./tests
    environment:
      FRONTEND_URL: http://frontend:80
      BACKEND_URL: http://backend:80
