version: "3.9"

services:
  # streamlit:
  #   build: ./streamlit
  #   platform: linux/amd64
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - ./llmops/src/rag_cot_evaluation/chroma_db:/app/llmops/src/rag_cot_evaluation/chroma_db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: pipenv run uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8004:8000"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
