site_name: Project Docs

nav:
  - Home: index.md
  - Computer Setup: computer_setup.md
  - Virtual Environment: virtual_environment.md
  - Code Quality: code_quality.md
  - Logging: logging.md
  - Documentation: documentation.md

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      execute: false
      include_source: true

watch:
  - src/proto_docs

theme:
  name: material
  features:
    - navigation.top
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 